name: sonarqube-analyze
permissions:
  contents: read
on:
  pull_request:
    branches: main
  workflow_dispatch:
jobs:
  sonarqube:
    name: Run SonarQube coverage analysis
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js LTS (Jod)
        uses: actions/setup-node@v4
        with:
          node-version: lts/Jod
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Prisma Generate
        run: pnpm prigen

      - name: Run tests
        run: pnpm run test --coverage

      - name: SonarQube analysis
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
